### ISSUE TITLE
CUDA Error

### ISSUE THREAD

**Issue by xpuctenjoyer** [serpotapov/Kohya_ss-GUI-LoRA-Portable#7]
`Cuda error: no kernel image is available for execution on the device`
I get this error shortly after hitting the "Train model" button. What I see in console right before the error is "loading image sizes" and building some cache. 

GPU: GeForce GTX TITAN X (Compute capability=5.2)
All the options are set to the bare minimum (batch=1, epochs=1, etc...)

Is there a way to fix this?

**Comment by xpuctenjoyer** [comment]
When I disable xformers I get another error: CUDA out of memory. My VRAM is 12gb, and using task manager I was able to confirm that all VRAM is used by the training process (no other VRAM significant processes are running)

**Comment by xpuctenjoyer** [comment]
I have also trying replacing the bitsandbytes_cuda dll and python code loading it (as discussed here https://github.com/kohya-ss/sd-scripts/issues/44). No effect

**Comment by serpotapov** [comment]
Hey 🖐
It looks like your videocard doesn't support Deep Learning applications.
Check your drivers and Windows.

**Comment by xpuctenjoyer** [comment]
After 2 more days I fixed it. I installed fresh portable kohya_ss UI, ran it - it showed some error regarding missing .dll required by pytorch. To fix this, I ran setup.bat, disabled "Use xformers" UI option and finally it's training. Not sure what fixed the CUDA memory limit issue
